# In your static/admin/config.yml file

backend: 
    name: github
    repo: christoph-phillips/blog

media_folder: static/assets
public_folder: assets

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Type", name: "type", widget: "select", multiple: true, options: [ "Run", "Bike" ], default: "Run"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "portfolio" # Used in routes, e.g., /admin/collections/blog
    label: "Portfolio" # Used in the UI
    folder: "content/portfolio" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Type", name: "type", widget: "select", multiple: true, options: [ "game", "application", "site", "data" ], default: "site"}
      - {label: "Created", name: "created", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Intro", name: "intro", widget: "markdown"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Features", name: "features", widget: "markdown"}
      - {label: "Link", name: "link", width: "string"}
      - {label: "Github", name: "github", width: "string"}
  - label: "Pages"
    name: "pages"
    # file collections are for uniquely designed content
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro text, name: intro, widget: text}
          - {label: Image, name: image, widget: image}
      - label: "Header"
        name: "header"
        file: "content/header.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Link1, name: link1, widget: string}
          - {label: Image1, name: image1, widget: image}
          - {label: Link2, name: link2, widget: string}
          - {label: Image2, name: image2, widget: image}
          - {label: Link3, name: link3, widget: string}
          - {label: Image3, name: image3, widget: image}
          
